### PR TITLE
Docker / CI CD Workflow

### PR DESCRIPTION
**Pull request by rayblair06**
- Implemented Docker via Dockerfile and docker-compose.
- Implemented github actions workflows for build and linting and tests.
- Changed default `DB_HOST=127.0.0.1` to use docker name of `postgres`.
- `npm run test` returns success exit code so pipeline doesn't fail, this will be changed to `jest` in future branch.

### CODE REVIEW

**Comment by Dmitry-White** [comment]
> WIP

Is it still a WIP?

**Comment by rayblair06** [comment]
@Dmitry-White I think I have mostly completed this although there is still parts I'm not happy with.

One being the time it takes `nodemon` to reset due to changes within the container, this takes at least 5/6 seconds on my machine which feels unnecessary long.

**Review by Dmitry-White — APPROVED** [review]
Don't know if you're done with the changes, but I'm already happy with what you're doing here.
I assume the split into Dev/Prod dockerfile to avoid deletion of node_modules on every change helped you to resolve the nodemon issue, right?
Also, really nice of you to use Github CI and Docker Compose on top of the requirement!
So, approving it for you to merge when you're happy with the changes

**Comment by rayblair06** [comment]
Thank you for taking the time to review my PR @Dmitry-White.

The change updates are still slower than I'd want but I think it's the best I can do at the moment, I may look at this further in the future.

**Pull request merged**
